[plugins]
php = "https://github.com/verzly/mise-php#latest"

[tools]
awscli = { version = "latest", symlink_bins = true }

java = { version = "temurin" }

flutter = { version = "latest" }

node = { version = "latest" }

bun = { version = "latest" }

pnpm = { version = "latest" }

deno = { version = "latest" }

ruby = { version = "latest" }

python = { version = "latest" }

go = { version = "latest" }

uv = { version = "latest" }

php = { version = "latest" }
